workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 20
      xcode: latest
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: "com.mingledtreasure.championshipconcierge"
        NODE_ENV: "production"
    scripts:
      - name: Install dependencies
        script: |
          npm install --include=dev
      - name: Build web assets
        script: |
          npx vite build --config vite.config.capacitor.ts
      - name: Add iOS platform
        script: |
          npx cap add ios || true
      - name: Set iOS deployment target
        script: |
          cd ios/App
          sed -i '' "s/platform :ios, '.*'/platform :ios, '15.0'/" Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' App.xcodeproj/project.pbxproj
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(date +%s)/60))
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing
        script: |
          cd ios/App
          xcode-project use-profiles --export-options-plist=~/export_options.plist
      - name: Update project signing
        script: |
          cd ios/App
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || true
          echo "CM_PROVISIONING_PROFILE_NAME: $CM_PROVISIONING_PROFILE_NAME"
          echo "TEAM_ID: $CM_TEAM_ID"
          ruby -e "
            require 'xcodeproj'
            project = Xcodeproj::Project.open('App.xcodeproj')
            project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
                config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Distribution'
                config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ENV['CM_PROVISIONING_PROFILE_NAME'] || ''
                config.build_settings['DEVELOPMENT_TEAM'] = ENV['CM_TEAM_ID'] || ''
              end
            end
            project.save
          " || echo "Ruby script failed, continuing..."
      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App
      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --path ios/App/build/ios/ipa/*.ipa
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
