workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 20
      xcode: latest
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: "com.mingledtreasure.championshipconcierge"
        NODE_ENV: "production"
        TEAM_ID: "CFFZ7YW46C"
    scripts:
      - name: Install dependencies
        script: |
          npm install --include=dev
      - name: Build web assets
        script: |
          npx vite build --config vite.config.capacitor.ts
      - name: Add iOS platform
        script: |
          npx cap add ios || true
      - name: Set iOS deployment target
        script: |
          cd ios/App
          sed -i '' "s/platform :ios, '.*'/platform :ios, '15.0'/" Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' App.xcodeproj/project.pbxproj
      - name: Fix Bundle ID before sync
        script: |
          cd ios/App
          sed -i '' 's/com\.mingledtreasures\.championshipconcierge/com.mingledtreasure.championshipconcierge/g' App.xcodeproj/project.pbxproj
          sed -i '' 's/com\.mingledtreasures\.championshipconcierge/com.mingledtreasure.championshipconcierge/g' App/Info.plist || true
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Reinstall CocoaPods
        script: |
          cd ios/App
          pod deintegrate || true
          pod install --repo-update
          - name: Fix Capacitor Framework Embedding
      script: |
        cd ios/App
        ruby -e "
        require 'xcodeproj'
        project = Xcodeproj::Project.open('App.xcodeproj')
        project.targets.each do |target|
          next unless target.name == 'App'
          embed_phase = target.build_phases.find { |p| p.respond_to?(:name) && p.name == 'Embed Frameworks' }
          if embed_phase
            embed_phase.files.each do |file|
              file.settings = { 'ATTRIBUTES' => ['CodeSignOnCopy', 'RemoveHeadersOnCopy'] }
            end
          end
        end
        project.save
        "    
      - name: Remove problematic Embed Pods script
        script: |
          cd ios/App
          ruby -e "
            require 'xcodeproj'
            project = Xcodeproj::Project.open('App.xcodeproj')
            project.targets.each do |target|
              target.shell_script_build_phases.each do |phase|
                if phase.name && phase.name.include?('Embed Pods Frameworks')
                  phase.remove_from_project
                end
              end
            end
            project.save
          " || echo "Ruby script failed, continuing anyway"     
      - name: Verify Bundle ID
        script: |
          cd ios/App
          echo "Bundle IDs in project:"
          grep -r "PRODUCT_BUNDLE_IDENTIFIER" App.xcodeproj/project.pbxproj
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(date +%s)/60))
      - name: Set up keychain
        script: |
          keychain initialize
            - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY
            
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Debug signing files
        script: |
          echo "=== Provisioning Profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No profiles found"
          echo ""
          echo "=== Code Signing Identities ==="
          security find-identity -v -p codesigning
          echo ""
          echo "=== Profile Details ==="
          for profile in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            echo "Profile: $profile"
            /usr/bin/security cms -D -i "$profile" 2>/dev/null | grep -A1 "Name\|UUID\|application-identifier" | head -10
            echo "---"
          done
      - name: Set up code signing
        script: |
          cd ios/App
          xcode-project use-profiles
      - name: Unlock keychain for codesigning
        script: |
          # Find and unlock Codemagic keychain
          KEYCHAIN=$(security list-keychains | grep -o '/[^"]*codemagic[^"]*' | head -1) || true
          if [ -n "$KEYCHAIN" ]; then
            security unlock-keychain -p "" "$KEYCHAIN" || true
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" "$KEYCHAIN" || true
          fi
          # Also try login keychain
          security unlock-keychain -p "" ~/Library/Keychains/login.keychain-db 2>/dev/null || true
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" ~/Library/Keychains/login.keychain-db 2>/dev/null || true      
      - name: Clean build folder
        script: |
          cd ios/App
          xcodebuild clean -workspace App.xcworkspace -scheme App
          rm -rf ~/Library/Developer/Xcode/DerivedData/*    
      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App \
            --clean
      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --path ios/App/build/ios/ipa/*.ipa
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
