workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 20
      xcode: latest
      groups:
        - ios_signing
      vars:
        BUNDLE_ID: "com.mingledtreasure.championshipconcierge"
        NODE_ENV: "production"
    scripts:
      - name: Install dependencies
        script: |
          npm install --include=dev
      - name: Build web assets
        script: |
          npx vite build --config vite.config.capacitor.ts
      - name: Add iOS platform
        script: |
          npx cap add ios || true
      - name: Set iOS deployment target
        script: |
          cd ios/App
          sed -i '' "s/platform :ios, '.*'/platform :ios, '15.0'/" Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' App.xcodeproj/project.pbxproj
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(date +%s)/60))
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@env:CM_CERTIFICATE_PRIVATE_KEY
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Install provisioning profiles
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          for profile in $HOME/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            echo "Found profile: $profile"
          done
          security find-identity -v -p codesigning
      - name: Build iOS app
        script: |
          cd ios/App
          TEAM_ID=$(security find-identity -v -p codesigning | grep "iPhone Distribution" | head -1 | sed 's/.*(\([A-Z0-9]*\)).*/\1/' || echo "")
          echo "Using Team ID: $TEAM_ID"
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            -allowProvisioningUpdates \
            archive
      - name: Export IPA
        script: |
          cd ios/App
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadSymbols</key>
              <true/>
              <key>destination</key>
              <string>export</string>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --path ios/App/build/ios/ipa/*.ipa
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
